kind: Namespace
apiVersion: v1
metadata:
  name: syslog-ng
  labels:
    name: syslog-ng
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng-deployment
  namespace: syslog-ng
  labels:
    app: syslog-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
    spec:
      containers:
      - name: syslog-ng
        image: balabit/syslog-ng:latest
        ports:
        - containerPort: 514
          protocol: UDP
        resources:
          requests:
            cpu: 250m
            memory: 524Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-syslog-ng
  namespace: syslog-ng
  labels:
    app.kubernetes.io/name: ingress-syslog-ng
    app.kubernetes.io/part-of: ingress-syslog-ng
spec:
  type: LoadBalancer
  ports:
    - name: syslog-ng
      port: 514
      targetPort: 514
      protocol: UDP
  selector:
    app.kubernetes.io/name: ingress-syslog-ng
    app.kubernetes.io/part-of: ingress-syslog-ng
